---
- hosts: all
  become: true
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python3 python-zipstream)
- name: Install zookeeper
  hosts: kafka
  become: true
  roles:
    - role: zookeeper
      sansible_zookeeper_hosts: zookeeper_nodes

- name: Install kafka
  hosts: kafka
  become: true
  roles:
    - role: kafka
      sansible_kafka_listen_address: "{{ ansible_default_ipv4.address }}"
      sansible_kafka_advertised_host_name: "{{ ansible_default_ipv4.address }}"
      sansible_kafka_zookeeper_hosts: zookeeper_nodes
