apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: digilocker-support-api
  name: digilocker-support-api
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: digilocker-support-api
  strategy: {}
  template:
    metadata:
      labels:
        k8s-app: digilocker-support-api
    spec:
      hostNetwork: true
      containers:
        - image: dockerhub/digilocker_support_api:1.0.56
          imagePullPolicy: Always
          name: digilocker-support-api
          envFrom:
            - configMapRef:
                name: divoc-config
      restartPolicy: Always
status: {}
