apiVersion: v1
kind: ConfigMap
metadata:
  name: divoc-config
  namespace: divoc
  selfLink: /api/v1/namespaces/divoc/configmaps/divoc-config
data:
  DB_HOST: "65.1.111.93"
  DB_PASSWORD: "registry123"
  ADMIN_API_CLIENT_SECRET: "b85c4cdb-40d4-46f3-8a75-f1756d118e97"
  DB_USER: "registry"
  DB_PORT: "5432"
  DB_DATABASE: "registry"
  ENABLE_CERTIFY_ACKNOWLEDGEMENT: ''
  KAFKA_BOOTSTRAP_SERVERS: "13.126.228.46:9092,52.66.189.108:9092,13.233.166.182:9092"
  KEYCLOAK_URL: 'http://keycloak-service:8080/auth'
  CACHE_TTL: "60"
  PUBLIC_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0WygguZf4umNIe4xoLvfMZtF4W1ufbhdtxiHAP9MhkS33qehg39H12dehhqTCHzihHrbm/3AimBWDOxFmLlTK5cuPwZAwOLqjoJfziAn4lE+2sarwbaKEA3/ChvioFhJRPnBBaUKDqomLeD7EVWCRwPS5W3+zcB9h67KI3/uo4L59vg6HD6xP/Z3MMkql2TmuHmJtBYsPweankxaXzfKOWIJtP/6Nhk13jYyBB65EitQ4RQnAFjmmEkCbJvB0szyeMdk4eA5OT4QXaGOk6v4BtMdE7kjk7334XhGGKA/XphEjRt/2x5IiB6uO/uYVUq5JqgAe87w2mqKiAwYgBiwCwIDAQAB"
  AUTH_PUBLIC_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArxV8BRY7CgWLtnujK3FkksIakYRK61hS/N6/v5a1bHluxlZeB65vpjtjlorch8S0183xuuY5pKie0X1SFgM5beGGaPQx08T8qj8N2ZVoY1sZGyR60+nDXCsz1NEM3OjVc6T7/BH2/sztmhfjBITy8GQwdZwdh9E0VLcTJjJV9a316f2q8ZDH8OGmTDw+mJmDJx7iKt8hSx5eeklVjeQ2rqecGhiqgHgKkaVYTB6t1zJot7HwlZop6eVH7/tvlv3c09ugYlcVefSnhGk795BUIcRqzHmpBQIkW3AZvonglfDTXz3D6234rgRHUTi//WvMFZ/JfjF3cE7mfREQnUBN1wIDAQAB"
  AUTH_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIIEoQIBAAKCAQEArxV8BRY7CgWLtnujK3FkksIakYRK61hS/N6/v5a1bHluxlZe\nB65vpjtjlorch8S0183xuuY5pKie0X1SFgM5beGGaPQx08T8qj8N2ZVoY1sZGyR6\n0+nDXCsz1NEM3OjVc6T7/BH2/sztmhfjBITy8GQwdZwdh9E0VLcTJjJV9a316f2q\n8ZDH8OGmTDw+mJmDJx7iKt8hSx5eeklVjeQ2rqecGhiqgHgKkaVYTB6t1zJot7Hw\nlZop6eVH7/tvlv3c09ugYlcVefSnhGk795BUIcRqzHmpBQIkW3AZvonglfDTXz3D\n6234rgRHUTi//WvMFZ/JfjF3cE7mfREQnUBN1wIDAQABAoIBAHYVjmy73pvWu7Ea\n2CUPuF5G7bZhPEpYarhD351vHvOHPxAj5g1WN9UszvEUvMIRCEtYigWdCxmj5GG0\nHS3dhNk4NvgIYqbKgAKuvj+Wxi3knh0xUGomim1acf3B9OP1YSk7B/ytfSHCwymf\nnKxKorNBT3GzFjOpBJtyUkb7wgAM8lkTSAmHiDzvN7aKCPU0sDxrtEIpWX/zUaGX\n2SgaLE8iBq6CJnF6Dkk8FgG4f/XUi+9WT3Dl5oQtUj2aP/vr/FVxzxNo+pw+Z4vq\nxiHjXbDy150q6OYAdZ86LPb+FU35xh+rmmo39ADeDIi/nLJ/Kup32YvJCQp0JBru\nm4RF3eECgYEA5wNxTDwY+dCsEX6+VvD6Te0C6xCGET0NW2Ni5cM7K0NQfBfD+rYI\nPm935BA3ljhy5/lR9GERQW4ATyjA3ISLALZ74PC5+5JTrE9CAY8GBeU6eJ9z0Ofu\nSJOu9w4KmM1TaXi3Xn2x2qKyPeA7roqUZfvclgj0En2mYaWPh0PwetECgYEAwgVn\nKcv4qSqHCz00PLF5xgCIt+MUalWotJ4uMpXBvnINDkWRYl0FuSzuPeQwnUAqkHUP\n1zBou5MRa70VrAoIkZEk2sSUbkzuihrf09bA/lZ7kVOcLH5k0r3A2EVGVCMWQ2II\n+1HLHdwkCWPx2lEJMBnH/xjbw6VBsfhzdEj6GCcCgYBQ0dOBaEUUoPyR4lWU9Rmc\nyZ6Lvmwo+8MAhfTDjVnV+ObfgzD9NVINBdJb55CK7ZTFs2QIqyzuRx20k/1lKLm4\nth8AwzdN3BOJ5PCiuvbQeTHLoX1TSNEEcyZzKGZsrujPrXv5guAGLYVOQHSgy7q/\nMy4pD1jUX0EmSFW+bPZlAQJ/egTr3F1rBPi59VeIgqMa8mtjkEI/lKBKeU0BwM5u\nClev3kniJPpbnxmiu0nHSR4Rpsf4Ll1DgLP9QMSp3Ihy2xltFCiNMNExM6mzGob0\n2P+KttreXR0gS2kK3viyQjfOyJHfFC9cjmrkPwOcFrDgFmAgZ04659AGgOa/tWIv\n5wKBgQCMLh1Ehkkv8yVrM4fyax8lYavCKiCQlxU7RNMp0c6KbPmTtf0527gFz8Yu\nKvHMzePQ8zO6mGkt5ZUX5kNsiOwZBMRTI7kMcgKUusR2k+Vf6VlzdnOzd9Wiwz56\nutY3s3BC6MCbZuVQrsBdtRQoLIHM6m7DkOdF/rFnzcGOwtqRvw==\n-----END RSA PRIVATE KEY-----\n"
  REGISTRY_URL: http://registry:8081
  REGISTRY_WITH_ES_URL: http://registry-es:8081
  REDIS_URL: "redis://52.66.181.44:6379"
  DISABLE_REGISTRY_CALL: ""
  DIGILOCKER_HMAC_AUTHKEY: "UPDATE_KEY_GIVEN_IN_DIGILOCKER"
  ENABLE_KEYCLOAK: "false"
  CLICK_HOUSE_URL: "tcp://192.168.0.26:9000?debug=true"
  CERTIFICATE_NAMESPACE: "https://divoc.egov.org.in/credentials/vaccination/v1"
  CERTIFICATE_NAMESPACE_V2: "https://divoc.egov.org.in/credentials/vaccination/v2"
  CERTIFICATE_CONTROLLER_ID: "https://divoc.egov.org.in/"
  CERTIFICATE_PUBKEY_ID: "https://example.com/i/divoc"
  CERTIFICATE_DID: "did:divoc-qa"
  CERTIFICATE_ISSUER: "https://divoc.egov.org.in"
  CERTIFICATE_BASE_URL: "https://divoc.egov.org.in/vaccine/"
  CERTIFICATE_FEEDBACK_BASE_URL: "https://divoc.egov.org.in/?"
  CERTIFICATE_INFO_BASE_URL: "https://divoc.egov.org.in/?"
  SIGNING_KEY_TYPE: "ED25519"
  CERTIFICATE_PUBLIC_KEY: "ARoP1iNrRMSksxjqp9AMMdY6Gk3FRwteQNshyPtTa8NN"
  CERTIFICATE_PRIVATE_KEY: "5vsfRNET9QDG72twFFCGLSYP6n9pDjdsz1R3PoHmZKAbYZYkLCNAWFKUDUgQGWCkRTYNcFkyne2BwvEsUzmBLiBU"
  CITIZEN_PORTAL_URL: "https://divoc.egov.org.in"
  #SMS_URL: "https://egovja.api.infobip.com/sms/2/text/advanced"
  #SMS_AUTH_KEY: "App 5dc1cd995acf0d9e7b039904047db277-b4958d86-c0b2-4825-94f9-ab7c5b140566"
  ENABLE_CERTIFIED_SMS: "false"
  ENABLE_SMS: "false"
  SENDER_EMAIL: "xxxx@mail.com"
  SENDER_PASSWORD: "xxxx"
