apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: flagr
  name: flagr
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: flagr
  strategy: {}
  template:
    metadata:
      labels:
        k8s-app: flagr
    spec:
      containers:
        - image: dockerhub/certificate_api:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "600m"
            limits:
              memory: "512Mi"
              cpu: "600m"
          name: flagr
          envFrom:
            - configMapRef:
                name: divoc-config
      restartPolicy: Always
status: {}
