apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: keycloak-service
  name: keycloak-service
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: keycloak-service
  strategy: {}
  template:
    metadata:
      labels:
        k8s-app: keycloak-service
    spec:
      containers:
        - image: dockerhub/keycloak:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "6Gi"
            limits:
              cpu: "500m"
              memory: "6Gi"
          name: keycloak-service
          env:
            - name: DB_ADDR
              value: divoc-jamaica-1.cmzsabksrd8k.us-east-1.rds.amazonaws.com
            - name: DB_DATABASE
              value: registry
            - name: DB_PASSWORD
              value: $5Ymvr8F#UkH
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_VENDOR
              value: postgres
            - name: KEYCLOAK_PASSWORD
              value: qP8q#8#KU38@
            - name: KEYCLOAK_USER
              value: admin
            - name: ENABLE_OTP_MESSAGE
              value: "true"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "192.168.60.105:9092"
      restartPolicy: Always
