apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: keycloak-service
  name: keycloak-service
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: keycloak-service
  strategy: {}
  template:
    metadata:
      labels:
        k8s-app: keycloak-service
    spec:
      containers:
        - image: dockerhub/keycloak:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          name: keycloak-service
          env:
            - name: DB_ADDR
              value: 65.1.111.93
            - name: DB_DATABASE
              value: registry
            - name: DB_PASSWORD
              value: registry123
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: registry
            - name: DB_VENDOR
              value: postgres
            - name: KEYCLOAK_PASSWORD
              value: qP8q#8#KU38@
            - name: KEYCLOAK_USER
              value: admin
            - name: ENABLE_OTP_MESSAGE
              value: "false"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "13.126.228.46:9092,52.66.189.108:9092,13.233.166.182:9092"
      restartPolicy: Always
