apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: keycloak
  namespace: divoc-qa
spec:
  maxReplicas: 50
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keycloak
  targetCPUUtilizationPercentage: 70