apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: keycloak
  name: keycloak
spec:
  ports:
    - name: "tcp-8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32080
  selector:
    k8s-app: keycloak
  sessionAffinity: None
  type: NodePort