apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: notification-service
  name: notification-service
spec:
  ports:
    - name: "8765"
      port: 8765
      targetPort: 8765
      nodePort: 32765
  selector:
    k8s-app: notification-service
  sessionAffinity: None
  type: NodePort