apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    k8s-app: notification-service
  name: notification-service
spec:
  ports:
    - name: "8765"
      port: 8765
      targetPort: 8765
  selector:
    k8s-app: notification-service
  sessionAffinity: None
  type: ClusterIP