apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    k8s-app: portal_api
  name: portal_api
spec:
  ports:
    - name: "tcp-8001"
      port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    k8s-app: portal_api
  sessionAffinity: None
  type: ClusterIP