apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: portal-api
  name: portal-api
spec:
  ports:
    - name: "tcp-8001"
      port: 8001
      protocol: TCP
      targetPort: 8001
      nodePort: 32001
  selector:
    k8s-app: portal-api
  sessionAffinity: None
  type: NodePort