apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  labels:
    k8s-app: registry
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: registry
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      labels:
        k8s-app: registry
    spec:
      containers:
        - env:
            - name: connectionInfo_password
              value: $5Ymvr8F#UkH
            - name: connectionInfo_uri
              value: jdbc:postgresql://divoc-jamaica-1.cmzsabksrd8k.us-east-1.rds.amazonaws.com:5432/registry
            - name: connectionInfo_username
              value: postgres
            - name: elastic_search_enabled
              value: "false"
            - name: registry_base_apis_enable
              value: "true"
            - name: taskExecutor_index_queueCapacity
              value: "100"
            - name: auditTaskExecutor_queueCapacity
              value: "100"
            - name: signature_enabled
              value: "false"
          image: dockerhub/registry-es:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
          #            limits:
          #              cpu: 500m
          name: registry
          ports:
            - containerPort: 8081
      restartPolicy: Always