apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    k8s-app: vaccination_api
  name: vaccination_api
spec:
  ports:
    - name: "tcp-8000"
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    k8s-app: vaccination_api
  sessionAffinity: None
  type: ClusterIP